### ISSUE TITLE
Sendblue is not a contructor

### ISSUE THREAD

**Issue by jakearmijo** [sendblue-api/sendblue-node#1]
### Sendblue is not a constructor

Hello I am following your GitHub and I am receiving the following error

```sh
const sendblue = new Sendblue(

TypeError: Sendblue is not a constructor
```
#### CODE BELOW

```JS
import Sendblue from "sendblue";
const sendblue = new Sendblue(
  process.env.SEND_BLUE_API_KEY,
  process.env.SEND_BLUE_SECRET
);
```

**Comment by jakearmijo** [comment]
At first, I thought it was due to me using just javascript. I converted everything to typescript and still had the same issue. I would like to contribute to this project if possible. Let me know if you see this message and if I can do something to try to help.

**Comment by elliottstorey** [comment]
Same problem here.

**Comment by elliottstorey** [comment]
Should be resolved now.
